webtalk_init -webtalk_dir /neuromorphic/home_dirs/andres/workspace/RECOG_KEN/kd_tree/kd_tree.sim/sim_1/impl/timing/xsim.dir/design_1_wrapper_sim_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 12 20:02:15 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "11aa45b7-6d4d-4a7a-ba60-86977f75bab1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4ac12effd0654c438b3260783bece375" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.4.1708 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3699.984 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "151136_KB" -context "xsim\\usage"
webtalk_transmit -clientid 138708572 -regid "" -xml /neuromorphic/home_dirs/andres/workspace/RECOG_KEN/kd_tree/kd_tree.sim/sim_1/impl/timing/xsim.dir/design_1_wrapper_sim_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /neuromorphic/home_dirs/andres/workspace/RECOG_KEN/kd_tree/kd_tree.sim/sim_1/impl/timing/xsim.dir/design_1_wrapper_sim_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /neuromorphic/home_dirs/andres/workspace/RECOG_KEN/kd_tree/kd_tree.sim/sim_1/impl/timing/xsim.dir/design_1_wrapper_sim_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
